### ISSUE TITLE
[BetterMediaPlayer] could not be compiled

### ISSUE THREAD

**Issue by FenekkuKitsune** [unknown81311/BetterMediaPlayer#20]
TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
    at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:61:33)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by doggybootsy** [comment]
What version are you on?

**Comment by FenekkuKitsune** [comment]
Latest, I double-checked.1.2.10

**Comment by doggybootsy** [comment]
The latest is 1.2.11. you need to download it off of github

**Comment by FenekkuKitsune** [comment]
Can it be updated in the plugin repo?

**Comment by doggybootsy** [comment]
It seems the repo never sent a webhook, since it was deleted. So i'll try to fix it
