### ISSUE TITLE
Couldn't Compile [2024]

### ISSUE THREAD

**Issue by zxxtlz** [unknown81311/BetterMediaPlayer#22]
``
TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
    at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:61:33)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
``

**Comment by zxxtlz** [comment]
had to install it from github.
