### ISSUE TITLE
cant be compiled

### ISSUE THREAD

**Issue by Tier6194** [unknown81311/BetterMediaPlayer#7]
TypeError: Cannot read property 'Controls' of undefined
    at plugin (betterdiscord://plugins/BetterMediaPlayer.plugin.js:195:67)
    at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:489:16)
    at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:490:7)
    at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:491:3)
    at Object.requireAddon (<anonymous>:4:39739)
    at Object.loadAddon (<anonymous>:4:9809)
    at Object.loadAddon (<anonymous>:4:37466)
    at AsyncFunction.<anonymous> (<anonymous>:4:7801)

**Comment by shelbyKiraM** [comment]
![image](https://user-images.githubusercontent.com/202692/196059331-02ef6f30-453c-48f8-8fe7-9248b64be97b.png)

**Comment by doggybootsy** [comment]
A fix is pending for review (or should), but you can download it directly
